const questionDB = {
  part1: [
    {id:'i001',maxMarks:1,question:`When it is 09 00 in Singapore, it is 11 00 in Melbourne. Madam Rohaya called her husband who was working in Melbourne at 01 30 Singapore time. What was the time in Melbourne when Madam Rohaya called her husband?`,solution:`09 00 → 11 00 (Melbourne is 2h ahead)
01 30 → 03 30
Ans: 03 30`,studentAnswer:`03 30`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`The student's answer matches the solution; correct format and value.`,summaryExplanation:`The final answer “03 30” exactly matches the required time; no units needed.`},
    {id:'i002',maxMarks:1,question:`Which two points (A, B, C and D) will form a right angle when we draw two straight lines from these two points to join to point X?

![Image](https://storage.googleapis.com/geniebook/images/question/Default Folder/19694a_qsn_img_0_1604936482.png)`,solution:`Points B and D`,studentAnswer:`bd`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Correct points but letters in lowercase so no credit.`,summaryExplanation:`Correct points chosen but lowercase “bd” violates capital-letter rule.`},
    {id:'i003',maxMarks:2,question:`342 min = ______ h ______ min`,solution:`300 min = 5 h
342 - 300 = 42
Ans: 5 h 42 min`,studentAnswer:`6h 10min`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Wrong conversion; did not show 5 h step.`,summaryExplanation:`Missing identification of 5 h and final time incorrect.`},
    {id:'i004',maxMarks:2,question:`600 s = ________ min _______ s`,solution:`10 min 0 s`,studentAnswer:`10 min`,correctMark:1,aiMark:1,aiConfidence:'low',stagedExplanation:`Seconds part omitted so final answer incomplete.`,summaryExplanation:`Found 10 min but missing “0 s”.`},
    {id:'i005',maxMarks:3,question:`Jane went shopping in 5 shops, average $5n per shop. She spent $45 in first shop and $6n more in second. What was the average amount spent in the remaining shops?`,solution:`Total 5×5n=25n
First two shops: 90+6n
Remaining: 19n-90
Average remaining: (19n-90)/3`,studentAnswer:`(31n-90)/3`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`First-step total correct but remaining expression wrong.`,summaryExplanation:`First two-shop total right; remaining and final average incorrect.`},
    {id:'i006',maxMarks:3,question:`Peter drew 2 semicircles and triangle PRS... diameters 14 cm and 10 cm. Find total area of shaded parts.`,solution:`Big semicircle 77 cm²
Triangle 49 cm²
Small semicircle 39 2/7 cm²
Shaded = 67 2/7 cm²`,studentAnswer:`Final 46 2/7 cm²`,correctMark:1,aiMark:2,aiConfidence:'high',stagedExplanation:`Areas of semicircles correct; final combination wrong.`,summaryExplanation:`Correct individual areas but combined result 46 2/7 cm² instead of 67 2/7 cm².`},
    {id:'i007',maxMarks:4,question:`Andy earned $4200, Brad $450 less. They spent $1900 and $1550 respectively. Difference between savings?`,solution:`Brad salary 3750
Andy save 2300
Brad save 2200
Difference $100`,studentAnswer:`Diff 100`,correctMark:3,aiMark:3,aiConfidence:'high',stagedExplanation:`Final answer missing dollar sign.`,summaryExplanation:`All intermediate values correct; final unit missing.`},
    {id:'i008',maxMarks:4,question:`Lights blink every 2 s, 5 s and 10 s. How many times blink together in 30 s?`,solution:`LCM 10 s, 30/10 = 3`,studentAnswer:`10`,correctMark:2,aiMark:1,aiConfidence:'low',stagedExplanation:`Found LCM 10 s but didn't convert 30 s or divide; final answer 10.`,summaryExplanation:`Identified 10 s interval; missed conversion and division, final 10 not 3.`}
  ],
  part2a: [
    {id:'a001',maxMarks:1,question:`Composite figure with semicircle, rectangle and circle. Find unshaded area.`,solution:`462 cm²`,studentAnswer:`462 cm²`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Answer value and unit correct.`,summaryExplanation:`Fully correct.`},
    {id:'a002',maxMarks:1,question:`Figure with centre G. Name angle same size as ∠CAG.`,solution:`∠GCA or ∠ACG`,studentAnswer:`gca`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Lowercase letters used.`,summaryExplanation:`Angle named correctly but not capitalised.`},
    {id:'a003',maxMarks:1,question:`Find 2¾ ÷ 3 in simplest fraction.`,solution:`11/12`,studentAnswer:`11/12`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Correct fraction.`,summaryExplanation:`Matches required value.`},
    {id:'a004',maxMarks:1,question:`In 108, the digit 1 is in the ______ place.`,solution:`hundreds`,studentAnswer:`hundred`,correctMark:0,aiMark:0,aiConfidence:'low',stagedExplanation:`Plural form required.`,summaryExplanation:`“hundred” not equivalent to “hundreds”.`},
    {id:'a005',maxMarks:2,question:`Scale diagram: find sum of values P and Q.`,solution:`P=0.88, Q=1.14, sum 2.02`,studentAnswer:`P:0.88 Q:1.14`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Intermediate values correct; sum missing.`,summaryExplanation:`Missing 2.02 final sum.`},
    {id:'a006',maxMarks:2,question:`36 girls took 79 beads each with 16 left. How many beads initially?`,solution:`2860`,studentAnswer:`2860`,correctMark:2,aiMark:2,aiConfidence:'high',stagedExplanation:`Working for 2844 not shown.`,summaryExplanation:`Final value correct but initial step missing.`},
    {id:'a007',maxMarks:2,question:`Net of solid: which solid forms?`,solution:`Solid D`,studentAnswer:`Solid C and D`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Multiple solids chosen.`,summaryExplanation:`Only Solid D fits the net.`},
    {id:'a008',maxMarks:2,question:`Which two children can buy 30¢ candy?`,solution:`Chloe and Adriel`,studentAnswer:`adriel`,correctMark:1,aiMark:0,aiConfidence:'high',stagedExplanation:`Totals for each child missing and only one name given.`,summaryExplanation:`Needs both Chloe and Adriel.`},
    {id:'a009',maxMarks:3,question:`Trip to Penang: 1/5 teachers, 2/3 of students boys. Fraction of people who were girls?`,solution:`4/15`,studentAnswer:`7/15`,correctMark:2,aiMark:2,aiConfidence:'high',stagedExplanation:`Steps for 4/5 and 1/3 shown; final subtraction wrong.`,summaryExplanation:`Final fraction should be 4/15.`},
    {id:'a010',maxMarks:3,question:`Eraser $x, pen $0.30 more, ruler $0.10 less than pen. Cost of 2 pens and 1 ruler?`,solution:`$(3x+0.80)`,studentAnswer:`$(x+0.80)`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Missing expressions for pen and ruler; final algebra wrong.`,summaryExplanation:`Needs (3x+0.80).`},
    {id:'a011',maxMarks:3,question:`Rectangular tank 40×30×36 cm, 5/6 full. Cubic tank 40 cm sides 5/8 full. After pouring until cube full, how much water left in rectangular tank (litres)?`,solution:`12 L`,studentAnswer:`37L`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Rectangular volume correct; extra volume wrong so final 37L.`,summaryExplanation:`Should be 12 L left.`},
    {id:'a012',maxMarks:3,question:`Terence drove 3/8 at 72 km/h, remaining 720 km. Overall average 76.8 km/h. Average speed for second part?`,solution:`80 km/h`,studentAnswer:`240 km/h`,correctMark:1,aiMark:2,aiConfidence:'low',stagedExplanation:`Total distance and time correct; final speed wrong.`,summaryExplanation:`Average should be 80 km/h.`},
    {id:'a013',maxMarks:4,question:`Eileen baked cupcakes, sold half, added 175 strawberry. Now 512. How many more chocolate than strawberry?`,solution:`499`,studentAnswer:`162`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Remaining chocolate 337 shown; total and difference missing/wrong.`,summaryExplanation:`Final difference should be 499.`},
    {id:'a014',maxMarks:4,question:`Harold had 520 beads, 35% black. After using 95 beads, 40% of remaining are black. How many red beads used?`,solution:`83`,studentAnswer:`113`,correctMark:3,aiMark:3,aiConfidence:'high',stagedExplanation:`Initial red, remaining total and red correct; final subtraction wrong.`,summaryExplanation:`Should be 83 red beads used.`},
    {id:'a015',maxMarks:4,question:`Andy $4200, Brad $450 less, spent 1900 and 1550. Difference in savings?`,solution:`$100`,studentAnswer:`300`,correctMark:2,aiMark:1,aiConfidence:'high',stagedExplanation:`Brad salary and savings incorrect; final difference 300 without $.`,summaryExplanation:`Correct difference is $100.`},
    {id:'a016',maxMarks:4,question:`Donuts $2.35, buy 8 get 1 free. Cost for 216 donuts?`,solution:`$451.20`,studentAnswer:`$451.2`,correctMark:3,aiMark:4,aiConfidence:'high',stagedExplanation:`Cost of 9 donuts not shown but final amount correct.`,summaryExplanation:`$451.2 equals $451.20 with correct unit.`}
  ],
  part2b: [
    {id:'b001',maxMarks:1,question:`Vani took part in a 2400 m race. She rested after 835 m and ran another 258 m before giving up. What is the distance she ran in all?`,solution:`1093 m`,studentAnswer:`835+258=1093`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Unit m missing so marked 0.`,summaryExplanation:`Correct number but missing unit.`},
    {id:'b002',maxMarks:1,question:`A printer prints 25 copies in 30 s. How long for 80 copies?`,solution:`96 s`,studentAnswer:`96`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Unit s missing.`,summaryExplanation:`Needs second unit.`},
    {id:'b003',maxMarks:1,question:`Mr Tan giving sweets: 12 each needs 38 more; 14 each needs 58 more. How many students?`,solution:`10`,studentAnswer:`10`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Answer correct.`,summaryExplanation:`Fully correct.`},
    {id:'b004',maxMarks:1,question:`Nancy is 5x years old. She will be 4 times Ronald in 8 years. Find Ronald's age in 8 years in terms of x.`,solution:`(5x+8)/4`,studentAnswer:`5x+8/4`,correctMark:0,aiMark:0,aiConfidence:'low',stagedExplanation:`Missing brackets alters fraction.`,summaryExplanation:`Should be (5x+8)/4.`},
    {id:'b005',maxMarks:2,question:`Scale diagram: sum of values P and Q.`,solution:`2.02`,studentAnswer:`P:0.88 Q:1.14`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Intermediate values given, sum missing.`,summaryExplanation:`Needed 2.02.`},
    {id:'b006',maxMarks:2,question:`Square garden 6m×6m divided into 3 equal rectangles. Area of each rectangle?`,solution:`12 m²`,studentAnswer:`12 cm²`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Value correct but wrong unit cm².`,summaryExplanation:`Unit should be m².`},
    {id:'b007',maxMarks:2,question:`Two square towels A and B. Perimeter A is twice B. B side 32 cm. Find perimeter of A.`,solution:`256 cm`,studentAnswer:`256`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Unit cm missing in final answer.`,summaryExplanation:`Should include cm.`},
    {id:'b008',maxMarks:2,question:`Sequence 711, 721, 741, __, 811, 861, __. Fill blanks.`,solution:`771, 921`,studentAnswer:`761, 921`,correctMark:1,aiMark:0,aiConfidence:'high',stagedExplanation:`First missing number incorrect.`,summaryExplanation:`Needs 771 and 921.`},
    {id:'b009',maxMarks:3,question:`Wendy 1 m 35 cm tall, 28 cm taller than Eden. Adele half as tall as total of Wendy and Eden. What is Adele's height (m and cm)?`,solution:`1 m 21 cm`,studentAnswer:`121 cm`,correctMark:2,aiMark:2,aiConfidence:'high',stagedExplanation:`Final not expressed in m and cm.`,summaryExplanation:`Answer should be 1 m 21 cm.`},
    {id:'b010',maxMarks:3,question:`Bales of rubber 375 kg each, cotton 126 kg. Find total mass of 12 rubber and 8 cotton bales.`,solution:`5508 kg`,studentAnswer:`12 bales of rubber:3000kg; 8 bales:1008`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Mass of rubber miscomputed; total missing.`,summaryExplanation:`Should total 5508 kg.`},
    {id:'b011',maxMarks:3,question:`Two overlapping rectangles with square overlap area 64 cm². Find area of unshaded parts.`,solution:`654 cm²`,studentAnswer:`510 cm²`,correctMark:0,aiMark:0,aiConfidence:'high',stagedExplanation:`Rectangle area and unshaded computation wrong.`,summaryExplanation:`Correct total unshaded area is 654 cm².`},
    {id:'b012',maxMarks:3,question:`Anwar's age this year multiple of 7, next year multiple of 5, between 20 and 80. How old in 6 years?`,solution:`55`,studentAnswer:`55`,correctMark:2,aiMark:3,aiConfidence:'low',stagedExplanation:`Present age 49 not shown.`,summaryExplanation:`Final 55 correct.`},
    {id:'b013',maxMarks:4,question:`Tank A 12×10×20 cm, 2/3 filled. Half poured into Tank B initially 1/5 full, filling to brim. Total capacity of two tanks (litres)?`,solution:`3.4 L`,studentAnswer:`3900L`,correctMark:1,aiMark:1,aiConfidence:'high',stagedExplanation:`Only Tank A volume correct; rest wrong.`,summaryExplanation:`Total capacity should be 3.4 L.`},
    {id:'b014',maxMarks:4,question:`Mr Lee took 7 h from A to B; Mr Wong 8 h from B to A. Started same time towards each other; after 3 h, 110 km apart. What was Mr Lee's speed?`,solution:`80 km/h`,studentAnswer:`80km/h`,correctMark:4,aiMark:4,aiConfidence:'high',stagedExplanation:`Answer correct with unit.`,summaryExplanation:`Fully correct.`},
    {id:'b015',maxMarks:4,question:`Jeremy, Kris, Lenny stickers: Lenny twice Kris, Kris twice Jeremy, Kris has 48. Total stickers?`,solution:`168`,studentAnswer:`264`,correctMark:2,aiMark:1,aiConfidence:'high',stagedExplanation:`Lenny count incorrect leading to wrong total.`,summaryExplanation:`Should total 168.`},
    {id:'b016',maxMarks:4,question:`Ahmad paid 2 $10 notes and 3 $2 notes for snacks costing $24.40. Change given in 50c and 20c coins. How many coins did he receive?`,solution:`5`,studentAnswer:`$1.60`,correctMark:2,aiMark:1,aiConfidence:'low',stagedExplanation:`Total paid not shown; coin breakdown missing; final answer is value not count.`,summaryExplanation:`He received 5 coins (two 50c and three 20c).`}
  ]
};
export { questionDB };
